'use client'

import { Button } from '@filecoin-foundation/ui-filecoin/Button'
import { SectionContent } from '@filecoin-foundation/ui-filecoin/SectionContent'

import { useCopyToClipboard } from '@/hooks/use-copy-to-clipboard'

import { SYNAPSE_CODE_SNIPPET } from '../data/synapse-code-snippet'

type IntegrateStorageSectionProps = {
  highlightedCode: string
}

export function IntegrateStorageSection({
  highlightedCode,
}: IntegrateStorageSectionProps) {
  const { copy, isCopied } = useCopyToClipboard()

  return (
    <SectionContent
      centerCTA
      centerTitle
      headingTag="h2"
      title="Integrate warm storage in your app"
      description="Get started with storage in just a few lines of code"
      cta={[
        <Button
          key="copy-code-snippet"
          onClick={() => copy(SYNAPSE_CODE_SNIPPET)}
          variant="primary"
          className="min-w-[200px]"
        >
          {isCopied ? 'Copied!' : 'Copy code snippet'}
        </Button>,
        <Button
          key="explore-documentation"
          href="https://github.com/FilOzone/filecoin-services/releases/tag/alpha%2Fcalibnet%2F0x80617b65FD2EEa1D7fDe2B4F85977670690ed348-v2"
          variant="ghost"
        >
          Explore documentation
        </Button>,
      ]}
    >
      <div className="synapse-code-wrapper mx-auto w-full max-w-[900px]">
        <div className="rounded-2xl overflow-hidden border border-gray-500/50 shadow-xl">
          <div className="synapse-code-titlebar flex items-center justify-between bg-[#020203]">
            <div className="flex items-center gap-2.5">
              <span className="lg:size-3.5 md:size-3 size-2 rounded-full bg-[#353535]" />
              <span className="lg:size-3.5 md:size-3 size-2 rounded-full bg-[#353535]" />
              <span className="lg:size-3.5 md:size-3 size-2 rounded-full bg-[#353535]" />
            </div>
            <span className="synapse-code-title text-xs text-gray-400 tracking-wide">
              synapse
            </span>
            <div className="synapse-code-spacer" />
          </div>
          <div
            className="synapse-code-block"
            // biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is generated by Shiki at build time
            dangerouslySetInnerHTML={{ __html: highlightedCode }}
          />
        </div>
      </div>
    </SectionContent>
  )
}
