import localFont from 'next/font/local'
import { clsx } from 'clsx'
import type { Metadata } from 'next'
import '@/styles/globals.css'
import { ReactNode } from 'react'
import { Header } from '@/components/Header'

const funnelSans = localFont({
  src: '../fonts/Funnel_Sans/FunnelSans[wght].woff2',
  display: 'swap',
  variable: '--font-funnel-sans',
  fallback: ['Arial', 'Helvetica', 'sans-serif'],
  preload: true,
})

const aspekta = localFont({
  src: '../fonts/Aspekta/AspektaVF.woff2',
  display: 'swap',
  variable: '--font-aspekta',
  fallback: ['Arial', 'Helvetica', 'sans-serif'],
  preload: true,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = Readonly<{ children: ReactNode }>

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={clsx(funnelSans.variable, aspekta.variable, 'antialiased')}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
